# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2e370ea67be50c364adc5353ba1166d2daf8d15d0862491f05ede5687873491fb99cad5924d836d14a8e7b534743e63876d48984bc3abfe4867b639016db4ca

test:
  secret_key_base: d067ab96ff10316f3399a560a932f32a3436ff705a455dfa5c9920b1f2205638d77e2d68dd0d364f236a541e09fa5344a456010a96c6c0038b59ef62b6d08d4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
